### ISSUE TITLE
{"name":"NotFoundError"}

### ISSUE THREAD

**Issue by ejatapibeda** [BeamlakAschalew/flixquest-api#1]
{"message":"Something went wrong. Please try again later.","error":{"name":"NotFoundError"}}

tmdb: https://www.themoviedb.org/tv/146176-berlin
on this link /watch-tv?tmdbId=146176&season=1&episode=1

error on every provider

does anyone know how to solve this?

**Comment by BeamlakAschalew** [comment]
I will fix it and update you

**Comment by BeamlakAschalew** [comment]
> {"message":"Something went wrong. Please try again later.","error":{"name":"NotFoundError"}}
> 
> tmdb: https://www.themoviedb.org/tv/146176-berlin on this link /watch-tv?tmdbId=146176&season=1&episode=1
> 
> error on every provider
> 
> does anyone know how to solve this?

It is fixed in the latest commit, try it and close the issue if it's working

**Comment by ejatapibeda** [comment]
Thanks
