### ISSUE TITLE
All active providers always give "Something went wrong. Please try again"

### ISSUE THREAD

**Issue by begalinsaf** [BeamlakAschalew/flixquest-api#24]
i tested it on locally, all providers such as showbox, vidsrcto, and vidsrc isnt working, even i try to clear `node_modules` then run `npm i` still not working

response
```javascript
{
  "message": "Something went wrong. Please try again",
  "error": {}
}
```

server log
```bash
Sinovice@Sinovice MINGW64 ~/Documents/NITIP/web/flixquest-api (main)
$ npm start

> flixquest-api@1.1.1 start
> ts-node src/index.ts

Starting server on port 3010... 🚀
{"level":30,"time":1710601371061,"pid":3088,"hostname":"Sinovice","msg":"Server listening at http://0.0.0.0:3010"}
server listening on http://0.0.0.0:3010
{"level":30,"time":1710601382174,"pid":3088,"hostname":"Sinovice","reqId":"req-1","req":{"method":"GET","url":"/vidsrc/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57893},"msg":"incoming request"}
{"level":30,"time":1710601382747,"pid":3088,"hostname":"Sinovice","reqId":"req-1","res":{"statusCode":500},"responseTime":572.633499994874,"msg":"request completed"}
{"level":30,"time":1710601761252,"pid":3088,"hostname":"Sinovice","reqId":"req-2","req":{"method":"GET","url":"/vidsrcto/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57973},"msg":"incoming request"}
{"level":30,"time":1710601761745,"pid":3088,"hostname":"Sinovice","reqId":"req-2","res":{"statusCode":500},"responseTime":492.9484999924898,"msg":"request completed"}
{"level":30,"time":1710601764521,"pid":3088,"hostname":"Sinovice","reqId":"req-3","req":{"method":"GET","url":"/showbox/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57977},"msg":"incoming request"}
{"level":30,"time":1710601764819,"pid":3088,"hostname":"Sinovice","reqId":"req-3","res":{"statusCode":500},"responseTime":297.4590999931097,"msg":"request completed"}
```

my `.env`
```env
PORT=3010
#TMDB API Read Access Token
TMDB_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdblablablabla

WORKERS_URL=https://blablabla.workers.dev
REDIS_HOST=redis-blablabla.ap-southeast-1-1.ec2.cloud.redislabs.com
REDIS_PASSWORD=jQPqblablablaKV6FP
REDIS_PORT=17702
```

**Comment by BeamlakAschalew** [comment]
> i tested it on locally, all providers such as showbox, vidsrcto, and vidsrc isnt working, even i try to clear `node_modules` then run `npm i` still not working
> 
> response
> ```javascript
> {
>   "message": "Something went wrong. Please try again",
>   "error": {}
> }
> ```
> 
> server log
> ```bash
> Sinovice@Sinovice MINGW64 ~/Documents/NITIP/web/flixquest-api (main)
> $ npm start
> 
> > flixquest-api@1.1.1 start
> > ts-node src/index.ts
> 
> Starting server on port 3010... 🚀
> {"level":30,"time":1710601371061,"pid":3088,"hostname":"Sinovice","msg":"Server listening at http://0.0.0.0:3010"}
> server listening on http://0.0.0.0:3010
> {"level":30,"time":1710601382174,"pid":3088,"hostname":"Sinovice","reqId":"req-1","req":{"method":"GET","url":"/vidsrc/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57893},"msg":"incoming request"}
> {"level":30,"time":1710601382747,"pid":3088,"hostname":"Sinovice","reqId":"req-1","res":{"statusCode":500},"responseTime":572.633499994874,"msg":"request completed"}
> {"level":30,"time":1710601761252,"pid":3088,"hostname":"Sinovice","reqId":"req-2","req":{"method":"GET","url":"/vidsrcto/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57973},"msg":"incoming request"}
> {"level":30,"time":1710601761745,"pid":3088,"hostname":"Sinovice","reqId":"req-2","res":{"statusCode":500},"responseTime":492.9484999924898,"msg":"request completed"}
> {"level":30,"time":1710601764521,"pid":3088,"hostname":"Sinovice","reqId":"req-3","req":{"method":"GET","url":"/showbox/watch-movie?tmdbId=763215","hostname":"localhost:3010","remoteAddress":"127.0.0.1","remotePort":57977},"msg":"incoming request"}
> {"level":30,"time":1710601764819,"pid":3088,"hostname":"Sinovice","reqId":"req-3","res":{"statusCode":500},"responseTime":297.4590999931097,"msg":"request completed"}
> ```
> 
> my `.env`
> ```env
> PORT=3010
> #TMDB API Read Access Token
> TMDB_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdblablablabla
> 
> WORKERS_URL=https://blablabla.workers.dev
> REDIS_HOST=redis-blablabla.ap-southeast-1-1.ec2.cloud.redislabs.com
> REDIS_PASSWORD=jQPqblablablaKV6FP
> REDIS_PORT=17702
> ```

Try using `proxied=false` if it still doesn't work show me the package.json file

**Comment by begalinsaf** [comment]
still doesnt work

**package.json**
```json
{
  "name": "flixquest-api",
  "version": "1.1.1",
  "description": "A node app that uses @movie-web/providers to scrape streaming sites",
  "main": "src/index.ts",
  "scripts": {
    "start": "ts-node src/index.ts",
    "dev": "nodemon src/index.ts",
    "lint": "prettier --write .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/cors": "^8.4.1",
    "@movie-web/providers": "git+https://github.com/BeamlakAschalew/mw-prod.git",
    "@types/dotenv": "^8.2.0",
    "axios": "^1.6.2",
    "chalk": "4.1.2",
    "cheerio": "^1.0.0-rc.12",
    "dotenv": "^16.3.1",
    "fastify": "^4.24.3",
    "ioredis": "^5.3.2",
    "prettier": "^3.1.0",
    "ts-node": "^10.9.1",
    "typescript": "5.0.2"
  },
  "devDependencies": {
    "@types/node": "^20.9.4"
  }
}

```

**Comment by BeamlakAschalew** [comment]
> still doesnt work
> 
> **package.json**
> ```json
> {
>   "name": "flixquest-api",
>   "version": "1.1.1",
>   "description": "A node app that uses @movie-web/providers to scrape streaming sites",
>   "main": "src/index.ts",
>   "scripts": {
>     "start": "ts-node src/index.ts",
>     "dev": "nodemon src/index.ts",
>     "lint": "prettier --write .",
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "@fastify/cors": "^8.4.1",
>     "@movie-web/providers": "git+https://github.com/BeamlakAschalew/mw-prod.git",
>     "@types/dotenv": "^8.2.0",
>     "axios": "^1.6.2",
>     "chalk": "4.1.2",
>     "cheerio": "^1.0.0-rc.12",
>     "dotenv": "^16.3.1",
>     "fastify": "^4.24.3",
>     "ioredis": "^5.3.2",
>     "prettier": "^3.1.0",
>     "ts-node": "^10.9.1",
>     "typescript": "5.0.2"
>   },
>   "devDependencies": {
>     "@types/node": "^20.9.4"
>   }
> }
> 
> ```

damn, okay delete the node_modules folder and delete the package.lock file also and run `npm i`

**Comment by BeamlakAschalew** [comment]
> > still doesnt work
> > 
> > **package.json**
> > ```json
> > {
> >   "name": "flixquest-api",
> >   "version": "1.1.1",
> >   "description": "A node app that uses @movie-web/providers to scrape streaming sites",
> >   "main": "src/index.ts",
> >   "scripts": {
> >     "start": "ts-node src/index.ts",
> >     "dev": "nodemon src/index.ts",
> >     "lint": "prettier --write .",
> >     "test": "echo \"Error: no test specified\" && exit 1"
> >   },
> >   "author": "",
> >   "license": "ISC",
> >   "dependencies": {
> >     "@fastify/cors": "^8.4.1",
> >     "@movie-web/providers": "git+https://github.com/BeamlakAschalew/mw-prod.git",
> >     "@types/dotenv": "^8.2.0",
> >     "axios": "^1.6.2",
> >     "chalk": "4.1.2",
> >     "cheerio": "^1.0.0-rc.12",
> >     "dotenv": "^16.3.1",
> >     "fastify": "^4.24.3",
> >     "ioredis": "^5.3.2",
> >     "prettier": "^3.1.0",
> >     "ts-node": "^10.9.1",
> >     "typescript": "5.0.2"
> >   },
> >   "devDependencies": {
> >     "@types/node": "^20.9.4"
> >   }
> > }
> > 
> > ```
> 
> damn, okay delete the node_modules folder and delete the package.lock file also and run `npm i`

other option would be downloading the new fresh copy of the repo and trying again

**Comment by begalinsaf** [comment]
I still get error code 500. I haven't changed anything here; I just set it up as directed in the readme. Maybe you can try it yourself by cloning this repo on your pc.

**Comment by BeamlakAschalew** [comment]
> I still get error code 500. I haven't changed anything here; I just set it up as directed in the readme. Maybe you can try it yourself by cloning this repo on your pc.

alright, I'll get back to you

**Comment by BeamlakAschalew** [comment]
> I still get error code 500. I haven't changed anything here; I just set it up as directed in the readme. Maybe you can try it yourself by cloning this repo on your pc.

I cloned it again and it's working, try putting the values of the environment variables in double quotes like so:

`TMDB_KEY="YOUR_TMDB_KEY"`


edit: I have found that that the env file variable values being in double quotes doesn't matter

**Comment by begalinsaf** [comment]
> > I still get error code 500. I haven't changed anything here; I just set it up as directed in the readme. Maybe you can try it yourself by cloning this repo on your pc.
> 
> I cloned it again and it's working, try putting the values of the environment variables in double quotes like so:
> 
> `TMDB_KEY="YOUR_TMDB_KEY"`
> 
> edit: I have found that that the env file variable values being in double quotes doesn't matter

its working now, `TMDB_KEY` must be using **API Key** not **API Read Access Token**

**Comment by begalinsaf** [comment]
maybe you need to update the readme to address this issue. Some people, like me, might be a bit confused, thanks bro

**Comment by BeamlakAschalew** [comment]
> maybe you need to update the readme to address this issue. Some people, like me, might be a bit confused, thanks bro 

Oh okay, I'm glad it worked for you
