### ISSUE TITLE
{     "message": "Something went wrong. Please try again",     "error": {         "name": "NotFoundError"     } }

### ISSUE THREAD

**Issue by ownerHZH** [BeamlakAschalew/flixquest-api#25]
req url: https://[flixquest-api.vercel.app/flixhq/watch-movie?tmdbId=18785](https://flixquest-api.vercel.app/flixhq/watch-movie?tmdbId=18785)

Response:

{     "message": "Something went wrong. Please try again",     "error": {         "name": "NotFoundError"     } }

**Comment by BeamlakAschalew** [comment]
> req url: https://[flixquest-api.vercel.app/flixhq/watch-movie?tmdbId=18785](https://flixquest-api.vercel.app/flixhq/watch-movie?tmdbId=18785)
> 
> 
> 
> Response:
> 
> {     "message": "Something went wrong. Please try again",     "error": {         "name": "NotFoundError"     } }

FlixHQ isn't working, working sources are shown using 🟢 emoji in the readme.

**Comment by stillmanpeeer** [comment]
try https://github.com/stillmanpeeer/rabbitstream

**Comment by BeamlakAschalew** [comment]
> try https://github.com/stillmanpeeer/rabbitstream
> 

Don't pay for piracy people

**Comment by stillmanpeeer** [comment]
It has a free plane you can use without paying, but there are some limits on daily usage.
