### ISSUE TITLE
Showbox error

### ISSUE THREAD

**Issue by streamamos** [BeamlakAschalew/flixquest-api#26]
I'm getting this error for a few days now on every single request for showbox:

{
"message": "Something went wrong. Please try again",
"error": {
"name": "NotFoundError"
}

**Comment by BeamlakAschalew** [comment]
> I'm getting this error for a few days now on every single request for showbox:
> 
> {
> "message": "Something went wrong. Please try again",
> "error": {
> "name": "NotFoundError"
> }

I don't know why it suddenly stopped working for you, maybe check the proxy if you're using one and don't use cloudflare proxy for showbox.

**Comment by streamamos** [comment]
Is it working for you? for example this link:
[https://flixquest-api.vercel.app/showbox/watch-tv?tmdbId=1399&season=1&episode=1](https://flixquest-api.vercel.app/showbox/watch-tv?tmdbId=1399&season=1&episode=1)

**Comment by streamamos** [comment]
> 
> I don't know why it suddenly stopped working for you, maybe check the proxy if you're using one and don't use cloudflare proxy for showbox.

Is it working for you? for example this link:
https://flixquest-api.vercel.app/showbox/watch-tv?tmdbId=1399&season=1&episode=1

**Comment by streamamos** [comment]
I fixed it, for some reason i now need to put "proxied=false" at the end.
