### ISSUE TITLE
Showbox not working again

### ISSUE THREAD

**Issue by begalinsaf** [BeamlakAschalew/flixquest-api#27]
latest update of this repo make showbox returning code 500

```json
{
    "message": "Something went wrong. Please try again",
    "error": {
        "name": "NotFoundError"
    }
}
```

A few days ago, I couldn't use Showbox due to a CORS 304 issue.

**Comment by BeamlakAschalew** [comment]
> latest update of this repo make showbox returning code 500
> 
> ```json
> {
>     "message": "Something went wrong. Please try again",
>     "error": {
>         "name": "NotFoundError"
>     }
> }
> ```
> 
> A few days ago, I couldn't use Showbox due to a CORS 304 issue.

I am intentionally sending error as a response since even if you get the video it's not playing

**Comment by begalinsaf** [comment]
Do you think this bug come from [@movie-web/providers](https://github.com/movie-web/providers)? I checked their Discord, and yes, they are currently fixing this issue.

**Comment by begalinsaf** [comment]
And I think Febbox updated their security, maybe that's why a few days ago I had CORS blocked issues for Showbox.

**Comment by BeamlakAschalew** [comment]
> Do you think this bug come from [@movie-web/providers](https://github.com/movie-web/providers)? I checked their Discord, and yes, they are currently fixing this issue.

Yes, of course

**Comment by begalinsaf** [comment]
its working now, thanks
